# -*- coding: utf-8 -*-
"""microspine_bar_chart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H4JqoIGB4g_KMzmmoSPqUNoRkcF3Vdyw
"""



from sklearn import preprocessing
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Ellipse
import matplotlib.transforms as transforms
import pandas as pd
import seaborn as sns

# Change the default font family
plt.rcParams['font.family'] = 'serif'
plt.rcParams["font.serif"] = "Times New Roman"

# Change the default font size
plt.rcParams['font.size'] = 16


# def confidence_ellipse(x, y, ax, n_std=3.0, facecolor='none', **kwargs):
#     """
#     Create a plot of the covariance confidence ellipse of *x* and *y*.

#     Parameters
#     ----------
#     x, y : array-like, shape (n, )
#         Input data.

#     ax : matplotlib.axes.Axes
#         The Axes object to draw the ellipse into.

#     n_std : float
#         The number of standard deviations to determine the ellipse's radiuses.

#     **kwargs
#         Forwarded to `~matplotlib.patches.Ellipse`

#     Returns
#     -------
#     matplotlib.patches.Ellipse
#     """
#     if x.size != y.size:
#         raise ValueError("x and y must be the same size")
#     norm_x = preprocessing.normalize([x])
#     norm_y = preprocessing.normalize([y])
#     cov = np.cov(norm_x, norm_y)
#     pearson = cov[0, 1]/np.sqrt(cov[0, 0] * cov[1, 1])
#     # Using a special case to obtain the eigenvalues of this
#     # two-dimensional dataset.
#     ell_radius_x = np.sqrt(1 + pearson)
#     ell_radius_y = np.sqrt(1 - pearson)
#     ellipse = Ellipse((0, 0), width=ell_radius_x * 2, height=ell_radius_y * 2,
#                       facecolor=facecolor, **kwargs)

#     # Calculating the standard deviation of x from
#     # the squareroot of the variance and multiplying
#     # with the given number of standard deviations.
#     scale_x = np.sqrt(cov[0, 0]) * n_std
#     mean_x = np.mean(norm_x)

#     # calculating the standard deviation of y ...
#     scale_y = np.sqrt(cov[1, 1]) * n_std
#     mean_y = np.mean(norm_y)

#     transf = transforms.Affine2D() \
#         .rotate_deg(45) \
#         .scale(scale_x, scale_y) \
#         .translate(mean_x, mean_y)

#     ellipse.set_transform(transf + ax.transData)
#     return ax.add_patch(ellipse)

# fig, ax_kwargs = plt.subplots(figsize=(6, 6))
# dependency_kwargs = [[-0.8, 0.5],
#                      [-0.2, 0.5]]
# mu = 2, -3
# scale = 6, 5

file_path = 'Batch Processing_Analysis.xlsx' # Change file name as needed
#B = str(file_path).split('_')[1].split('.')[0]
#ax_kwargs.set_title(B.upper())
sheet_name = 'Final Stats'
df = pd.read_excel(file_path, sheet_name=sheet_name, usecols='H:I', skiprows=19)

sns.set_style("white") #Options: deep, muted, bright, pastel, dark, colorblind

# Plt the mean with cross mark
#ax_kwargs.scatter(df['Del X1'].mean(), df['Del Y1'].mean(), c='blue', s=3, marker='x')


# x0 = df['Del X1 cm']
# x00 = x0.to_numpy()
# #x00.reshape(1, -1)
# y0 = df['Del Y1 cm']
# y00 = y0.to_numpy()
# #y00.reshape(1, -1)

# x1 = preprocessing.normalize(x0.data)
# scaled_x1 = pd.DataFrame(x1, columns=x0.data.columns)
# #x1 = preprocessing.normalize([x00])
# y1 = preprocessing.normalize([y00])
# print(x1.shape)
# x2 = 'Del X2 cm'
# y2 = 'Del Y2 cm'
# x3 = 'Del X3 cm'
# y3 = 'Del Y3 cm'



# Data
barWidth = 0.3

bars = df['Disp (cm)']
bars1= [bars[0],bars[3],bars[6],bars[9]]
bars2= [bars[1],bars[4],bars[7],bars[10]]
bars3= [bars[2],bars[5],bars[8],bars[11]]

errors = df['StdDev']
error1= [errors[0],errors[3],errors[6],errors[9]]
error2= [errors[1],errors[4],errors[7],errors[10]]
error3= [errors[2],errors[5],errors[8],errors[11]]

# bars1 = [12, 30, 1, 8, 22]
# bars2 = [28, 6, 16, 5, 10]
# bars3 = [29, 3, 24, 25, 17]

# Bar positions
r = np.arange(len(bars1))
r2 = r + barWidth
r3 = r2 + barWidth

# Plotting
fig, ax = plt.subplots(dpi=300)
ax.bar(r, bars1, color='#73ad93', width=barWidth, edgecolor='green', label='0ML', yerr =error1, capsize=3)
ax.bar(r2, bars2, color='#bcbfbd', width=barWidth, edgecolor='gray', label='1ML', yerr =error2, capsize=3)
ax.bar(r3, bars3, color='#b0524c', width=barWidth, edgecolor='red', label='2ML', yerr =error3, capsize=3)

# Xticks
#ax.set_xlabel('group', fontweight='bold')
ax.set_ylabel('cm', fontweight='bold')
ax.set_xticks(r + barWidth)
ax.set_xticklabels(['Concrete', 'Brick', 'Sand', 'Forest Floor'], fontweight='bold')

# Legend and show
ax.legend()
ax.title.set_text('Average Trial Displacement Per Surface')
ax.title.set_fontweight('bold')
plt.show()




#Other stuff
barWidth2 = 0.1

#Actual delta x,y data (inlcuding negatives which indicates direction)
b1= [-0.02, -0.01] #0ML delta x
b2= [0.01, 0.00] #0ML delta y
b3= [0.62, 0.10] #1ML delta x
b4= [-0.16, -0.14] #1ML delta y
b5= [0.19, 0.20] #2ML delta x
b6= [-0.14, -0.10] #2ML delta y

e1= [0.14, 0.03]
e2= [0.09, 0.02]
e3= [0.36, 0.13]
e4= [0.52, 0.12]
e5= [0.19, 0.24]
e6= [0.16, 0.29]

# #Absolute delta x,y data (only cares about magnitude of data)
# b1= [0.07, 0.02] #0ML delta x
# b2= [0.06, 0.01] #0ML delta y
# b3= [0.65, 0.22] #1ML delta x
# b4= [0.44, 0.19] #1ML delta y
# b5= [0.20, 0.13] #2ML delta x
# b6= [0.15, 0.15] #2ML delta y

# e1= [0.12, 0.03]
# e2= [0.07, 0.02]
# e3= [0.31, 0.22]
# e4= [0.33, 0.24]
# e5= [0.18, 0.09]
# e6= [0.15, 0.11]

# Bar positions
r = np.arange(len(b1))
r2 = r + barWidth2
r3 = r2 + barWidth2
r4 = r3 + barWidth2
r5 = r4 + barWidth2
r6 = r5 + barWidth2

# Plotting
fig1, ax = plt.subplots(dpi=300)
ax.bar(r, b1, color='#73ad93', width=barWidth2, edgecolor='green', label='0ML $\Delta$ X', hatch='*', yerr =e1, capsize=3)
ax.bar(r2, b2, color='#73ad93', width=barWidth2, edgecolor='green', label='0ML $\Delta$ Y', yerr =e2, capsize=3)
ax.bar(r3, b3, color='#bcbfbd', width=barWidth2, edgecolor='gray', label='1ML $\Delta$ X', hatch='*', yerr =e3, capsize=3)
ax.bar(r4, b4, color='#bcbfbd', width=barWidth2, edgecolor='gray', label='1ML $\Delta$ Y', yerr =e4, capsize=3)
ax.bar(r5, b5, color='#b0524c', width=barWidth2, edgecolor='red', label='2ML $\Delta$ X', hatch='*', yerr =e5, capsize=3)
ax.bar(r6, b6, color='#b0524c', width=barWidth2, edgecolor='red', label='2ML $\Delta$ Y', yerr =e6, capsize=3)

# Xticks
#ax.set_xlabel('group', fontweight='bold')
ax.set_ylabel('cm', fontweight='bold', fontsize='14')
ax.set_xticks(r + barWidth2 + barWidth2)
ax.set_xticklabels(['Concrete', 'Brick'], fontweight='bold', fontsize='14')
ax.tick_params(axis='y', which='major', labelsize=12)

# Legend and show
ax.legend(fontsize='12')
ax.title.set_text('Average $\Delta$ X and $\Delta$ Y Per Gait')
ax.title.set_fontweight('bold')
ax.title.set_fontsize('14')

fig1.set_figheight(4)
plt.show()


# sns.scatterplot(x=x1, y=y1, data=df, ax=ax_kwargs,color=[117/255, 174/255, 148/255],label='0ML')

# confidence_ellipse(df['Del X2 cm'], df['Del Y2 cm'], ax_kwargs,
#                    alpha=0.2, facecolor=[189/255, 192/255, 190/255], edgecolor='white', zorder=0,label='_nolegend_')
# sns.scatterplot(x='Del X2 cm', y='Del Y2 cm', data=df, ax=ax_kwargs, color=[189/255, 192/255, 190/255],label='1ML')

# confidence_ellipse(df['Del X3 cm'], df['Del Y3 cm'], ax_kwargs,
#                    alpha=0.2, facecolor=[178/255, 87/255, 81/255], edgecolor='red', zorder=0,label='_nolegend_')
# sns.scatterplot(x='Del X3 cm', y='Del Y3 cm', data=df, ax=ax_kwargs,color=[178/255, 87/255, 81/255],label='2ML')

# confidence_ellipse(df['Del X1 cm'], df['Del Y1 cm'], ax_kwargs,
#                    facecolor=[117/255, 174/255, 148/255], edgecolor='green', zorder=0, label='_nolegend_')


# Change legend order
# handles, labels = ax_kwargs.get_legend_handles_labels()
# h0 = handles[0]
# h2 = handles[1]
# h1 = handles[2]
# l1 = labels[0]
# l2 = labels[1]
# l0 = labels[2]
# new_order = ['0ML', '1ML', '2ML']
# ax_kwargs.legend([h0,h2,h1], [l0,l2,l1])
# handles, labels = plt.get_legend_handles_labels()
# handle_dict = dict(zip(labels, handles))
# new_handles = [handle_dict[label] for label in new_order]
# plt.legend(handles=new_handles, labels=new_order)
# plt.legend()

# # axis title
# ax_kwargs.set_xlabel('$\Delta$ X (cm)')
# ax_kwargs.set_ylabel('$\Delta$ Y (cm)')

# # bold the axis title
# ax_kwargs.xaxis.label.set_fontweight('bold')
# ax_kwargs.yaxis.label.set_fontweight('bold')

# # increase font size
# ax_kwargs.xaxis.label.set_fontsize(14)
# ax_kwargs.yaxis.label.set_fontsize(14)

# # increase the legend size
# ax_kwargs.legend(fontsize=14)

# # Increase tick size
# #ax_kwargs.tick_params(axis='both', which='major', labelsize=24)

# # Increase the title size
# ax_kwargs.title.set_text('Concrete')
# ax_kwargs.title.set_fontsize(20)
# ax_kwargs.title.set_fontweight('bold')

# # increase number of ticks
# ax_kwargs.locator_params(axis='x', nbins=8)
# ax_kwargs.locator_params(axis='y', nbins=8)

# ax_kwargs.axvline(c='grey', lw=0.5)
# ax_kwargs.axhline(c='grey', lw=0.5)

# #legend = plt.legend(title='Robots', loc='upper left', frameon=True, shadow=True, borderpad=1)
# plt.show()